version: '3.8'

services:

  nodejs:
    build:
      context: ../
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis-cluster-creator
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis-node1:
    build:
      context: redis
    ports:
      - "7000:7000"
      - "17000:17000"
    restart: always
    entrypoint: ["redis-server", "/etc/redis/rediscluster.conf", "--port", "7000", "--cluster-announce-ip", "redis-node1"]
  redis-node2:
    build:
      context: redis
    ports:
      - "7001:7001"
      - "17001:17001"
    restart: always
    entrypoint: ["redis-server", "/etc/redis/rediscluster.conf", "--port", "7001", "--cluster-announce-ip", "redis-node2"]
  redis-node3:
    build:
      context: redis
    ports:
      - "7002:7002"
      - "17002:17002"
    restart: always
    entrypoint: ["redis-server", "/etc/redis/rediscluster.conf", "--port", "7002", "--cluster-announce-ip", "redis-node3"]
  redis-node4:
    build:
      context: redis
    ports:
      - "7003:7003"
      - "17003:17003"
    restart: always
    entrypoint: ["redis-server", "/etc/redis/rediscluster.conf", "--port", "7003", "--cluster-announce-ip", "redis-node4"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node5:
    build:
      context: redis
    ports:
      - "7004:7004"
      - "17004:17004"
    restart: always
    entrypoint: ["redis-server", "/etc/redis/rediscluster.conf", "--port", "7004", "--cluster-announce-ip", "redis-node5"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node6:
    build:
      context: redis
    ports:
      - "7005:7005"
      - "17005:17005"
    restart: always
    entrypoint: ["redis-server", "/etc/redis/rediscluster.conf", "--port", "7005", "--cluster-announce-ip", "redis-node6"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-cluster-creator:
    image: redis  
    entrypoint: ["/bin/sh", "-c", "echo 'yes' | redis-cli --cluster create redis-node1:7000 redis-node2:7001 redis-node3:7002 redis-node4:7003 redis-node5:7004 redis-node6:7005 --cluster-replicas 0"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

volumes:
  postgres_data:
  redis_data:
