version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis-1:
    image: redis:latest
    container_name: redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data_1:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-2:
    image: redis:latest
    container_name: redis-2
    ports:
      - "6380:6379"
    volumes:
      - redis_data_2:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-3:
    image: redis:latest
    container_name: redis-3
    ports:
      - "6381:6379"
    volumes:
      - redis_data_3:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-4:
    image: redis:latest
    container_name: redis-4
    ports:
      - "6382:6379"
    volumes:
      - redis_data_4:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-5:
    image: redis:latest
    container_name: redis-5
    ports:
      - "6383:6379"
    volumes:
      - redis_data_5:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-6:
    image: redis:latest
    container_name: redis-6
    ports:
      - "6384:6379"
    volumes:
      - redis_data_6:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-7:
    image: redis:latest
    container_name: redis-7
    ports:
      - "6385:6379"
    volumes:
      - redis_data_7:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-8:
    image: redis:latest
    container_name: redis-8
    ports:
      - "6386:6379"
    volumes:
      - redis_data_8:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-9:
    image: redis:latest
    container_name: redis-9
    ports:
      - "6387:6379"
    volumes:
      - redis_data_9:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-10:
    image: redis:latest
    container_name: redis-10
    ports:
      - "6388:6379"
    volumes:
      - redis_data_10:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  redis_data_1:
  redis_data_2:
  redis_data_3:
  redis_data_4:
  redis_data_5:
  redis_data_6:
  redis_data_7:
  redis_data_8:
  redis_data_9:
  redis_data_10:
